---
- hosts: crawler
  vars_files:
    - secrets/vars.yml
  tasks:
    - name: Clone repo in temp location
      git: clone=yes depth=1 version={{op_tag}}
        repo:https://github.com/gaspaio/operaprices.git
        dest:/tmp/operaprices

    - name: Ensure data dir exists
      file: path=/data state=directory mode=0755

    - name: rebuild docker images
      command: make build ENV={{op_env}}chdir=/tmp/operaprices

    - name: redeploy container
      command: make deploy ENV={{op_env}} chdir=/tmp/operaprices

    - name: remove temp location
      file: path=/tmp/operaprices state=absent

